# Generated by Django 5.2.7 on 2025-11-09 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='base.student'),
        ),
    ]
